server:
  port: 9094

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AnalyticsDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: root
      password: 1234



authservice:
 secret:
  secret-key: ${JAVA_14_SECRET_KEY:123}
  issuer: ${JAVA_14_ISSUER:123}
